import type { Metadata } from "next";
import { gambetta } from "@/src/assets/fonts/gambetta";
import { anekLatinCondensed } from "@/src/assets/fonts/anekLatin";
import { AccessibilityModalProvider } from "@/src/context/AccessibilityModalContext"
import AccessibilityModal from "@/src/components/accessibility/AccessibilityModal"
import { AccessibilityProvider } from '@/src/context/AccessibilityContext';


import "./globals.css";
import FloatingBar from "../components/floatingbar/FloatingBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gambetta.variable} ${anekLatinCondensed.variable} antialiased`}
      >
        <AccessibilityModalProvider>
          <AccessibilityProvider>
            {children}
            <FloatingBar />
            <AccessibilityModal />
          </AccessibilityProvider>
        </AccessibilityModalProvider> 
      </body>
    </html>
  );
}
